### ISSUE TITLE
Seems like the Parser doesn't utilize the config

### ISSUE THREAD

**Issue by sitch** [tlux/file_size#7] opened 2020-09-23 22:14 UTC
adding:
```elixir
config :file_size, :symbols, %{
  b: "B",
  kb: "k",
  mb: "M",
  gb: "G",
  tb: "T"
}
```

Still fails for 
```elixir
iex> FileSize.parse("1 k")                                  
{:error, %FileSize.ParseError{reason: :unit, value: "1 k"}}

```

**Comment by tlux** [comment] 2020-09-25 12:46
Currently, this is by design. Because, when you have multiple applications using file_size in the same project, you would be able globally override the parser behavior for all applications which can lead to unexpected behavior.

However, for your use case it would be possible to introduce `FileSize.parse/2` (similar to `FileSize.format/2`) so we could pass some options to the parser, for example:

```elixir
FileSize.parse("1 k", symbols: %{kb: "k", m: "M"})
```

You are very welcome to open a pull request. :) 
Closing this for now.

**Closed as completed by tlux** 2020-09-25 12:46 UTC
